version: "3.3"
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  hostr:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  postgres:
    driver: local
