version: "3.3"
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hostr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog
    # network_mode: service:app
    logging:
      driver: "none" # disable saving logs
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp server

volumes:
  postgres:
    driver: local
