version: "3.5"

services:
  shiny:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{project_id}}.rule=Host(`{{project_id}}.cargoship.stackocean.com`)" # TODO: Change with your own domain
      - "traefik.http.routers.{{project_id}}.tls.certresolver=default"
      - "traefik.http.routers.{{project_id}}.entrypoints=websecure"
      - "traefik.http.services.{{project_id}}.loadbalancer.server.port=3838"
networks:
  web:
    external: true
