name: Checks
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
